### ISSUE TITLE
Allow `tsconfig.json` to be overridden?

### ISSUE THREAD

**Issue by samzhao** [guestlinelabs/oc-template-typescript-react#3]
Hey,

Thanks so much for creating this package!

I was wondering if it's possible to create a custom `tsconfig.json` to override the default one provided as part of the compiler?

**Comment by ricardo-devis-agullo** [comment]
Hi, sorry for the late reply. Last version exposes tsconfig so you can override it (some settings are needed so if you try to change them will be overriden again, same as [CRA](https://create-react-app.dev/) does)
