### ISSUE TITLE
Server-side rendering fails

### ISSUE THREAD

**Issue by diessica** [guestlinelabs/oc-template-typescript-react#51]
Hi 😺 👋  New to OC and have recently setup a registry and components, still getting myself onboarded but so far so good! This template is really a time saver but unfortunately I haven't gotten SSR to work. I've followed the setup instructions, SSR works just fine with [oc-template-react](https://github.com/opencomponents/oc-template-react), and I haven't touched the dummy component provided by the template.

When req the component via my registry, that's the response I get:
```
{
  "code": "INTERNAL_SERVER_ERROR",
  "error": {
    "name": "TypeError",
    "message": "Cannot read properties of undefined (reading 'indexOf')",
    "stack": "TypeError: Cannot read properties of undefined (reading 'indexOf')\n    at module.exports (/workspace/node_modules/minimal-request/src/index.js:11:34)\n    at /workspace/node_modules/oc-template-typescript-react/lib/to-be-published/get-js-from-url.js:6:3\n    at module.exports (/workspace/node_modules/oc-template-typescript-react/lib/to-be-published/try-get-cached.js:13:3)\n    at module.exports [as render] (/workspace/node_modules/oc-template-typescript-react/lib/render.js:24:5)\n    at Object.renderTemplate (/workspace/node_modules/oc-client/src/template-renderer.js:23:18)\n    at returnResult (/workspace/node_modules/oc/dist/registry/routes/helpers/get-component.js:272:32)\n    at /workspace/node_modules/oc/dist/registry/routes/helpers/get-component.js:309:29\n    at /workspace/node_modules/universalify/index.js:22:54\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
  },
  "name": "header-ts",
  "requestVersion": ""
}                                                                                                  
```

I dived into it and```options.model.reactComponent``` used by [render.js](https://github.com/guestlinelabs/oc-template-typescript-react/blob/master/packages/oc-template-typescript-react/lib/render.js#L10) is empty, therefore missing the URL required by the model. ([`minimal-request` does not handle missing URLs gracefully](https://github.com/matteofigus/minimal-request/blob/3c11eb49b70ae5304ada46d5b6b21ceebe23eddf/src/index.js#L11), hence `Cannot read properties of undefined (reading 'indexOf')`).

The [pure React template's higherOrderServerTemplate sends URL down](https://github.com/opencomponents/oc-template-react/blob/6fdd9feff98df5605f9756cbfb93652f080e8bd7/packages/oc-template-react-compiler/lib/higherOrderServerTemplate.js#L22) to the model. Is there any reason why [the same does not happen in higherOrderServerTemplate](https://github.com/guestlinelabs/oc-template-typescript-react/blob/b61104a9c962a1d288a3c101c1581da386387a31/packages/oc-template-typescript-react-compiler/lib/higherOrderServerTemplate.js#L21)? I'll keep giving things a shot, but I wonder if there could be something else I am missing while setting up the template.

**Comment by ricardo-devis-agullo** [comment]
When moving this template from 2 http requests (template.js and react-component.js) to one (template.js), this information got lost. Should be easy to re-add. I'll prepare a PR when I have some time

**Comment by ricardo-devis-agullo** [comment]
Hi, this should've been fixed on the latest version
```
"oc-template-typescript-react": "4.1.0",
"oc-template-typescript-react-compiler": "5.1.4",
```
